### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by pablolemosassis** [inspirit/CaptureDevice#1]
I think there is an error with source paths:

The Main.as calls:
import ru.inspirit.asfeat.capture.CaptureDeviceInfo

While the structure is in fact:
ru.inspirit.capture.CaptureDeviceInfo

I've tried to correct that, but couldn't make it work at all on my Mac or my iPhone.

**Comment by inspirit** [comment]
hey, u right Main.as wasn't update since last version. now i fixed it to work with latest version.
i will add special demo for mobiles that get use of new options like power of 2 data from camera so u can render it to screen using stage3d and GPUImage framework ;)
