### ISSUE TITLE
xcode complains about missing files

### ISSUE THREAD

**Issue by makc** [inspirit/CaptureDevice#2]
![](http://i49.tinypic.com/2lyvja.png)

how do I fix this, or did you forget to upload these files?

**Comment by inspirit** [comment]
hmm it looks like u opened 2 projects as one... osx and ios are separate at least onmy machine :)

**Comment by makc** [comment]
this is what I get when opening native/osx/captureOSX.xcodeproj

**Comment by inspirit** [comment]
and what happen if u open captureIOS project?

**Comment by makc** [comment]
this:
![](http://i47.tinypic.com/jkvdw2.png)

**Comment by inspirit** [comment]
well i guess u can try to compile first. and u can remove captureIOS reference from OSX project.
but u should also provide correct link to AIR framework to compile it.

**Comment by makc** [comment]
both projects do not compile because of missing pch files, I do clean build folder / build but it always complain about pch even before getting to air part

**Comment by inspirit** [comment]
че-то глючит гит-хаб конечно.. обновил теперь есть эти файлы но еще откуда-то появились маковские темп-файлы. хотя я их не вижу локально... вообще это precompiled headers file по идее он одолжен перегенериться

**Comment by makc** [comment]
я тоже так подумал ибо в визуалстудии pch всегда генерились сами. однако в гугле пишут, что pch в икскоде это типа часть исходников, а из них генерятся gch уже

**Comment by makc** [comment]
добрался до ошибки с air sdk думаю можно закрывать
