### ISSUE TITLE
black screen on ipad

### ISSUE THREAD

**Issue by makc** [inspirit/CaptureDevice#8]
I finally got to compile actual ipa with this :) The code was

``` actionscript3
package com.example{

  import ru.inspirit.capture.CaptureDevice;
  import flash.text.TextField;
  import ru.inspirit.capture.CaptureDeviceInfo;
  import flash.events.Event;
  import flash.display.Sprite;

  public class Main extends Sprite {
    private var capture : CaptureDevice ;
    private var tf : TextField ;
    public function Main(  ){
      tf = new TextField();
      tf.autoSize = "left";
      tf.textColor = 0xFF00;
      addChild(tf);
      try {
        CaptureDevice.initialize();
        var device : CaptureDeviceInfo  = CaptureDevice.getDevices(false)[0];
        capture = new CaptureDevice(device.name, 320, 240);
        capture.setupForDataType(CaptureDevice.GET_FRAME_BITMAP);
        addEventListener(Event.ENTER_FRAME, onEnterFrame);
        tf.text = "OK";
      } catch ( e : Error ) {
        tf.text = "SHIT :( " + e.toString();
      }
    }
    private function onEnterFrame ( e : Event ) : void {
      var newFrame : Boolean  = capture.requestFrame(CaptureDevice.GET_FRAME_BITMAP);
      if ( newFrame ) {
        graphics.clear();
        graphics.beginBitmapFill(capture.bmp);
        graphics.drawRect(0, 0, 320, 240);
      }
    }
  }
}
```

App compiles and installs on device with no problem, however all I have is this [black screen](http://i47.tinypic.com/2i6ihrt.png). No crash reports, nothing.

What did I miss?

**Comment by inspirit** [comment]
who knows? :) can u look through device logs?.. it should report what was requested and how was it going. if smth goes wrong it certainly should log it

**Comment by makc** [comment]
папка логов пуста ( а ipa-debug и ipa-test вообще не собираются почему-то

```
Exception in thread "main" java.lang.Error: Unable to find named traits: ru.inspirit.capture::CaptureDeviceInfo
```

а, гугл говорит This is probably because you have not included the extension in your application.xml.

**Comment by inspirit** [comment]
похоже компилятор глючит... я компилил этот билд и под айфон и под айпёд без проблем...
все же видимо надо сесть и пересобрать его конкретно что я уже давно планирую с доп фукциями под мобильные типа вспышки и всего остального...

**Comment by makc** [comment]
с вышеозначенным фиксом заработало. почему в ipa-debug-interpreter собирается без него - непонятно.
